name: Generate stats card

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: Generate stats.svg
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=Tushar-07-byte&hide_title=false&hide_rank=true&show_icons=true&include_all_commits=true&theme=dracula&locale=en&hide_border=true&custom_title=GitHub%20Stats
          path: dist/stats.svg
          token: ${{ secrets.GH_STATS_TOKEN }}

      - name: Publish stats.svg
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: stats-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
